name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: rakudo-star:latest

    steps:
    - uses: actions/checkout@v2

    - name: Raku version
      run: raku -v
        
    - name: Install lib dependecies
      run: apt-get -qq update && apt-get -qq install -y libssl1.1 libssl-dev openssl

    - name: Install dependencies
      run: zef install --deps-only --/test --test-depends .

    - name: Run tests
      run: zef test -v --debug .
